### ISSUE TITLE
Questions about reproducibility of the results present on the paper

### ISSUE THREAD

**Issue by bruAristimunha** [Navidfoumani/EEG2Rep#1]
Hello @Navidfoumanin!

Your super cool article appeared on my radar this week, and I had the pleasure of reading it and really enjoying it!

You did a great job comparing the baselines, and your method has a lot of nice details about the masking, and good self-supervised training (I personally find SSL very challenging with EEG)!

I noted that you cited and drew parallels with shallowNet and sleep Chambon, which I appreciated!

I'm still studying your code, but I already have two initial questions:

1) I couldn't quite understand how you established the baselines in your code, I think it's a necessary sub-product to your paper! Even if it's not necessarily as nice as your code. I know that some models are not open for example, e.g. MAEEG.

2) I also realized that it is not very clear how to generate the results for each figure in the article, and how to just run or get your model as a feature extractor. I think an extra polish on the readme would be enough!

I was wondering if you help me with my questions.

All the best,

**Comment by Navidfoumani** [comment]
Hi @bruAristimunha,
Thank you so much for taking the time to read my article and for your encouraging words! I'm pleased to know that you found it interesting. Your feedback is much appreciated.

All the points you mentioned are already on my top to-do list. Despite a busy schedule, I'm committed to addressing them and plan to have everything fixed by the end of this month.

I'll make sure to keep you updated on the progress.

Kind regards,
Navid

**Comment by bruAristimunha** [comment]
Hey @Navidfoumani!

By any chance any update on this? I can help if necessary :)

**Comment by Navidfoumani** [comment]
Dear Bru,
Thank you once again for getting in touch. I'm currently actively working on the code and aim to release a user-friendly version soon. The exciting news is that the upcoming version will also include cross-domain training capabilities.
